# Generated by Django 2.2.16 on 2022-06-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="author",
            new_name="following",
        ),
    ]
